import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import "@/app/assets/styles/index.scss";

import SideMenu from '@/app/components/SideMenu/SideMenu'
import ServiceWorkerRegistry from '@/app/components/ServiceWorkerRegistry'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: '#000000',
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json", // マニフェストファイルのパスを指定
  appleWebApp: {
    capable: true,
    title: "My PWA", // iOS用
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ServiceWorkerRegistry />
        <SideMenu />
        <main className="main">
          {children}
        </main>
      </body>
    </html>
  );
}
